<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net60;netstandard2.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Sodium.Functional</PackageId>
    <MinVerTagPrefix>dotnet-functional-</MinVerTagPrefix>
    <Product>Sodium Functional for C#</Product>
    <Title>Sodium Functional for C#</Title>
    <Description>Sodium Functional - Functional constructs for C#.</Description>
    <AssemblyName>Sodium.Functional</AssemblyName>
    <RootNamespace>Sodium.Functional</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DocumentationFile>bin\Debug\Sodium.Functional.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DocumentationFile>bin\Release\Sodium.Functional.xml</DocumentationFile>
  </PropertyGroup>

</Project>
