<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net472</TargetFramework>
    </PropertyGroup>

    <PropertyGroup>
        <AssemblyName>Sodium.Frp.Tests.Performance</AssemblyName>
        <RootNamespace>Sodium.Frp.Tests.Performance</RootNamespace>
        <EnableDefaultItems>false</EnableDefaultItems>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="OptimizedPriorityQueue" Version="4.1.1" />
        <PackageReference Include="System.ValueTuple" Version="4.4.0" />
    </ItemGroup>

    <ItemGroup>
      <Compile Include="Program.cs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Sodium.Core.Frp\Sodium.Core.Frp.csproj" />
      <ProjectReference Include="..\Sodium.Frp\Sodium.Frp.csproj" />
      <ProjectReference Include="..\Sodium.Functional\Sodium.Functional.csproj" />
    </ItemGroup>

</Project>
