<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net60;netstandard2.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SodiumFRP</PackageId>
    <MinVerTagPrefix>dotnet-csharp-</MinVerTagPrefix>
    <Product>Sodium FRP for .NET</Product>
    <Title>Sodium FRP for .NET</Title>
    <Description>Sodium - Functional Reactive Programming (FRP) library for .NET.</Description>
    <AssemblyName>Sodium.Frp</AssemblyName>
    <RootNamespace>Sodium.Frp</RootNamespace>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DocumentationFile>bin\Debug\Sodium.Frp.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DocumentationFile>bin\Release\Sodium.Frp.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ValueTuple" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Behavior.cs" />
    <Compile Include="BehaviorExtensionMethods.cs" />
    <Compile Include="BehaviorLoop.cs" />
    <Compile Include="BehaviorSinkExtensionMethods.cs" />
    <Compile Include="Cell.cs" />
    <Compile Include="CellExtensionMethods.cs" />
    <Compile Include="CellLoop.cs" />
    <Compile Include="CellSinkExtensionMethods.cs" />
    <Compile Include="CellStreamSinkExtensionMethods.cs" />
    <Compile Include="CleanupExtensionMethods.cs" />
    <Compile Include="JetBrainsAnnotations.cs" />
    <Compile Include="Listener.cs" />
    <Compile Include="LoopedBehaviorExtensionMethods.cs" />
    <Compile Include="LoopedCellExtensionMethods.cs" />
    <Compile Include="LoopedStreamExtensionMethods.cs" />
    <Compile Include="MutableListenerExtensionMethods.cs" />
    <Compile Include="Operational.cs" />
    <Compile Include="Stream.cs" />
    <Compile Include="StreamExtensionMethods.cs" />
    <Compile Include="StreamLoop.cs" />
    <Compile Include="StreamSinkExtensionMethods.cs" />
    <Compile Include="Transaction.cs" />
    <Compile Include="Time\ITimer.cs" />
    <Compile Include="Time\ITimerSystem.cs" />
    <Compile Include="Time\ITimerSystemImplementation.cs" />
    <Compile Include="Time\SecondsTimerSystem.cs" />
    <Compile Include="Time\SystemClockTimerSystem.cs" />
    <Compile Include="Time\TimerSystem.cs" />
    <Compile Include="Time\TimerSystemImplementationBase.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Sodium.Core.Frp\Sodium.Core.Frp.csproj" />
    <ProjectReference Include="..\Sodium.Functional\Sodium.Functional.csproj" />
  </ItemGroup>

</Project>
