<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net472;net60;netstandard2.0</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>SodiumFRP.Async</PackageId>
        <Authors>SodiumFRP</Authors>
        <PackageLicenseUrl>http://opensource.org/licenses/MIT</PackageLicenseUrl>
        <PackageProjectUrl>https://github.com/SodiumFRP/sodium</PackageProjectUrl>
        <Version>1.0.0</Version>
        <PackageVersion>1.0.0</PackageVersion>
        <AssemblyVersion>1.0.0.0</AssemblyVersion>
        <FileVersion>1.0.0.0</FileVersion>
        <InformationalVersion>1.0.0.0</InformationalVersion>
        <Company>SodiumFRP</Company>
        <Product>Sodium FRP Async for C#</Product>
        <Title>Sodium FRP Async for C#</Title>
        <Description>Sodium FRP Async Extensions library for C#.</Description>
        <IncludeSource>True</IncludeSource>
        <IncludeSymbols>True</IncludeSymbols>
        <AssemblyName>Sodium.Frp.Async</AssemblyName>
        <RootNamespace>Sodium.Frp.Async</RootNamespace>
        <EnableDefaultItems>false</EnableDefaultItems>
        <Nullable>enable</Nullable>
        <LangVersion>10</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
        <PackageReference Include="System.ValueTuple" Version="4.4.0"/>
    </ItemGroup>

    <ItemGroup>
      <Compile Include="AsyncConcurrencyStrategy.cs" />
      <Compile Include="MapAsyncExtensions.cs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Sodium.Core.Frp.Async\Sodium.Core.Frp.Async.csproj" />
      <ProjectReference Include="..\..\..\CSharp\Sodium.Functional\Sodium.Functional.csproj" />
    </ItemGroup>

</Project>
