<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
    </PropertyGroup>

    <PropertyGroup>
        <AssemblyName>Sodium.Frp.Tests</AssemblyName>
        <RootNamespace>Sodium.Frp.Tests</RootNamespace>
        <EnableDefaultItems>false</EnableDefaultItems>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
        <PackageReference Include="NUnit" Version="3.11.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="3.10.0" />
        <PackageReference Include="System.ValueTuple" Version="4.4.0" />
    </ItemGroup>

    <ItemGroup>
      <Compile Include="BehaviorTests.cs" />
      <Compile Include="CellTests.cs" />
      <Compile Include="CommonTests.cs" />
      <Compile Include="DenotationalSemanticsTests.cs" />
      <Compile Include="EitherTests.cs" />
      <Compile Include="IssueTests.cs" />
      <Compile Include="LoopTests.cs" />
      <Compile Include="MaybeExtensionMethodsTests.cs" />
      <Compile Include="MaybeTests.cs" />
      <Compile Include="PerformanceTests.cs" />
      <Compile Include="StreamTests.cs" />
      <Compile Include="TimerTests.cs" />
      <Compile Include="TransactionTests.cs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Sodium.Core.Frp\Sodium.Core.Frp.csproj" />
      <ProjectReference Include="..\Sodium.Frp\Sodium.Frp.csproj" />
      <ProjectReference Include="..\Sodium.Functional\Sodium.Functional.csproj" />
    </ItemGroup>

</Project>
