<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net60;netstandard2.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SodiumFRP.Core</PackageId>
    <MinVerTagPrefix>dotnet-core-</MinVerTagPrefix>
    <Product>Sodium FRP Core for .NET</Product>
    <Title>Sodium FRP Core for .NET</Title>
    <Description>Sodium - Functional Reactive Programming (FRP) library for .NET core library.</Description>
    <AssemblyName>Sodium.Core.Frp</AssemblyName>
    <RootNamespace>Sodium.Frp</RootNamespace>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ValueTuple" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="AssemblyInfo.cs" />
    <Compile Include="Behavior.cs" />
    <Compile Include="BehaviorExtensionMethods.cs" />
    <Compile Include="BehaviorSink.cs" />
    <Compile Include="Cell.cs" />
    <Compile Include="CellExtensionMethods.cs" />
    <Compile Include="CellSink.cs" />
    <Compile Include="CellStreamSink.cs" />
    <Compile Include="Cleanup.cs" />
    <Compile Include="CoalesceHandler.cs" />
    <Compile Include="EntryPriorityQueue.cs" />
    <Compile Include="LazyBehavior.cs" />
    <Compile Include="LazyExtensionMethods.cs" />
    <Compile Include="Listener.cs" />
    <Compile Include="LoopedBehavior.cs" />
    <Compile Include="LoopedCell.cs" />
    <Compile Include="LoopedStream.cs" />
    <Compile Include="Maybe.cs" />
    <Compile Include="MutableListener.cs" />
    <Compile Include="Node.cs" />
    <Compile Include="Operational.cs" />
    <Compile Include="Stream.cs" />
    <Compile Include="StreamExtensionMethods.cs" />
    <Compile Include="StreamListenerManager.cs" />
    <Compile Include="StreamSink.cs" />
    <Compile Include="Transaction.cs" />
    <Compile Include="Unit.cs" />
    <Compile Include="Utilities.cs" />
  </ItemGroup>

</Project>
