<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
    </PropertyGroup>

    <PropertyGroup>
        <AssemblyName>Sodium.Frp.Tests.Memory</AssemblyName>
        <RootNamespace>Sodium.Frp.Tests.Memory</RootNamespace>
        <EnableDefaultItems>false</EnableDefaultItems>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.dotMemoryUnit" Version="3.0.20171219.105559" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
        <PackageReference Include="NUnit" Version="3.11.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="3.10.0" />
        <PackageReference Include="OptimizedPriorityQueue" Version="4.1.1" />
    </ItemGroup>

    <ItemGroup>
      <Compile Include="StreamTests.cs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Sodium.Core.Frp\Sodium.Core.Frp.csproj" />
      <ProjectReference Include="..\Sodium.Frp\Sodium.Frp.csproj" />
    </ItemGroup>

</Project>
