module Warning where

warning = [
    "DO NOT EDIT THIS FILE",
    "It was generated by \"common tests\" - please modify it in the common source and it",
    "will be re-generated for all languages."
  ]

